apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-frontend-02cn
  name: web-frontend-02cn
  namespace: zero-to-cloud-native
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-frontend-02cn
  strategy: {}
  template:
    metadata:
      labels:
        app: web-frontend-02cn
    spec:
      imagePullSecrets:
        - name: all-icr-io
      containers:
      - name: web-frontend-02cn
        image: us.icr.io
        ports:
          - containerPort: 80
        resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 25m
              memory: 32Mi
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: web-frontend-02cn
  name: web-frontend-02cn
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  - name: http
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: web-frontend-02cn
  type: LoadBalancer
