apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: web-frontend-02cn
  name: web-frontend-02cn
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: web-frontend-02cn
  type: LoadBalancer
status:
  loadBalancer: {}
