apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: web-frontend-02cn
  name: web-frontend-02cn
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web-frontend-02cn
  type: ClusterIP
status:
  loadBalancer: {}
